version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint-config-prettier
    versions:
    - 7.2.0
    - 8.0.0
    - 8.1.0
    - 8.2.0
  - dependency-name: mathjs
    versions:
    - 9.1.0
    - 9.2.0
    - 9.3.0
    - 9.3.1
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: sharp
    versions:
    - 0.27.1
    - 0.27.2
    - 0.28.0
  - dependency-name: "@nuxt/content"
    versions:
    - 1.11.1
    - 1.12.0
    - 1.13.1
  - dependency-name: sass-loader
    versions:
    - 10.1.1
    - 11.0.0
